DATA SEGMENT
RESULT DB ?
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:
    MOV AX, DATA
    MOV DS,AX
    MOV AL,24
    MOV BL,36
    ADD AL,BL
    MOV RESULT,AL
    CODE ENDS
END START
