DATA SEGMENT
    RESULT DB ?
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    
START:
    MOV AX, DATA
    MOV DS, AX
    MOV AL,[0001]
    MOV BL,[0002]
    ADD AL, BL
    MOV RESULT,AL
    INT 21H 
    CODE ENDS
END START
    